assets/resource/base/pipeline/tasks/LoungeTasks.json
=> Dev - imporve LoungeTasks

assets/interface.json, assets/resource/pipeline/TimeLimitedTasks/claimIntelligenceSupplyStaminaTask.json, assets/resource/pipeline/TimeLimitedTasks/claimSevenDayCheckInResourceTask.json, assets/resource/pipeline/public/PrepareDailyTasks/BoundaryAdvance/BoundaryAdvance.json, assets/resource/pipeline/public/PrepareDailyTasks/Email/getNewEmails.json, assets/resource/pipeline/public/PrepareDailyTasks/Shop/shop.json, assets/resource/pipeline/public/PrepareDailyTasks/StaminaReplenishments/staminaReplenishment.json, assets/resource/pipeline/public/PrepareDailyTasks/Warehouse/organizeWarehouse.json, assets/resource/pipeline/public/PrepareDailyTasks/Warehouse/weaponAccessories.json, assets/resource/pipeline/public/PrepareDailyTasks/timeLimited/timeLimitedTask.json, assets/resource/pipeline/tasks/PrepareDailyTasks.json
开了个外服号看了一下官方英文翻译，目前只处理了 `PrepareDailyTasks` 的部分
=> chore: 将部分命名调整成游戏内官方英文描述

README.md
=> doc(更新自述文档)

assets/resource/pipeline/public/ClaimRewardTasks/passSystem.json, scripts/json_to_mermaid.py
=> fix: 付费通行证跳过确认节点

README.md
=> docs: new avatar

assets/interface.json, assets/resource/pipeline/public/SimulatedCombat/liveDrillCombatLogic.json, scripts/json_to_mermaid.py
=> fix: 切换战斗速度死循环

assets/resource/pipeline/public/ClaimRewardTasks/passSystem.json, assets/resource/pipeline/public/ClaimRewardTasks/supportDollRewards.json
=> refactor: 通行证

assets/resource/pipeline/public/ClaimRewardTasks/passSystem.json, assets/resource/pipeline/public/PublicAreaDailyTasks/dispatchCenter.json
=> feat: 发送手动处理派遣的通知

assets/resource/pipeline/public/PublicAreaDailyTasks/dispatchCenter.json
=> fix: 派遣进行中不发送通知

assets/interface.json, assets/resource/pipeline/public/ClaimRewardTasks/passSystem.json, assets/resource/pipeline/public/PrepareDailyTasks/BoundaryAdvance/BoundaryAdvance.json, assets/resource/pipeline/public/PrepareDailyTasks/Email/getNewEmails.json, assets/resource/pipeline/public/PublicAreaDailyTasks/dispatchCenter.json, assets/resource/pipeline/public/VersionActivity/enterVersionActivityResourceSweep.json, assets/resource/pipeline/public/controlButton.json
用公共区的功能测试了一下，语法没问题，把仓库里所有的 focus 都顺手改了
有的场景（比如调研邮件）实在不好触发，就没有都测试，只测了一个 focus
=> refactor: 调整 focus 属性格式

assets/resource/pipeline/tasks/AutoSweepBattle.json
当前配件满了也没提醒，容易体力满了不管，用户也没发现任务没执行，所以加了一个提醒
测过了
=> feat: 添加武器配件存储上限提示信息

assets/interface.json, assets/resource/pipeline/public/SimulatedCombat/wargameSimulation.json
全自动兵棋推演，自动领取奖励，检测到领取满参与奖励后，自动停止兵棋推演
测过了
=> feat: 全自动兵棋推演

.github/workflows/install.yml
=> chore: 恢复 macOS 版本

assets/interface.json, assets/resource/pipeline/public/PrepareDailyTasks/Storeroom/flower.json, assets/resource/pipeline/public/PrepareDailyTasks/Storeroom/organizeStoreroom.json
=> feat: 拆解生长数据

assets/resource/pipeline/public/PrepareDailyTasks/Storeroom/weapon.json
=> feat: 添加武器拆解通知的识别与确认逻辑

assets/resource/pipeline/public/ClaimRewardTasks/dangerousExcavation.json
=> fix: 更新险境挖掘任务的逻辑，添加滑动查找功能并调整后续步骤

scripts/json_to_mermaid.py
之前给maa core提了个issue，他们现在支持jsonc了，我们这里的现在也适配上了
=> feat(json_to_mermaid): 支持解析带注释的 JSONC 文件

assets/resource/base/pipeline/public/PublicAreaDailyTasks/dispatchCenter.json
fix https://github.com/DarkLingYun/MaaGF2Exilium/issues/120
=> feat: OCR未识别到再次派遣回退逻辑

assets/resource/base/pipeline/public/活动层/美味烹调.json, assets/resource/base/pipeline/public/活动层/茶歇一刻.json, assets/resource/base/pipeline/public/活动层/逸趣导算.json
- 在多个 JSON 文件中新增“活动层等级提升”相关的状态和下一步操作
- 包含“美味烹调”、“茶歇一刻”和“逸趣导算”的等级提升配置
- 每个等级提升状态均添加了识别和预期操作
=> feat: 为活动层新增多个等级提升配置及相关操作

assets/resource/base/pipeline/public/ClaimRewardTasks/trial.json, assets/resource/base/pipeline/public/通用战斗.json
- 新增超时设置和中断任务识别
- 添加多个新任务状态，包括自动战斗和人形介绍界面
- 优化任务流程，提升用户体验
=> refactor: 使用通用战斗进行预演

assets/resource/base/pipeline/public/SimulatedCombat/wargameSimulation.json
=> fix: 通用战斗超时延长
